



look into "drum tech"
meets monday nights

https://www.reddit.com/r/uofm/comments/lecrfq/are_there_any_300level_humanities_about/
can potentially take SMTD upper level theory/composition courses

# music minor

PAT courses, can I take courses outside of the ones on the sheet
will music minor complete my general electives requirement?
will I be charged at the CoE rate per credit hour?

Video Game Music Pat 305 / MUSPERF 300 sounds really interesting

This course surveys game music from the first synthesized “bleeps” and “bloops” to modern orchestral compositions. Techniques are learned to aurally analyze game music. Students will create compositions using computer software as a final project. Course is designed for non-music majors; the ability to read standard music notation is not needed.

u/LoHershal:
I have two favorite classes:

    EECS 281 - Introduction to Data Structures and Algorithms. This is a class you'd only find interesting, or one you'd only ever take if you are in EECS. Despite the high workload, I found everything I learnt to be extremely interesting and I had a lot of fun doing the projects.

-PAT 305/MUSPERF 300 (Numbers may have changed) - Video Game Music. Again, if you don't like video games then you probably won't get much from this. It's a really chill, yet engaging course about how music in video games is constructed, how it's meant to play with our mind and emotions, and how it differs from music in other media. Like I said, it's a very relaxed 2 credit course, there's not a lot of work until the very end with the big "Compose your own music" project. The professor for the class is also extremely invested into the material he's teaching, and that just makes the class so much more fun. On top of that, I met some really cool people in the class with similar interests to me, which boosted my enjoyment even more.

u/wedgieratts
pat 412, digital music ensemble. a semester studying pauline oliveros & meditating .... got a lot out of it.


PAT 412: Digital Music Ensemble

https://smtd.umich.edu/departments/conducting/ensembles/digital-music-ensemble/

Digital Music Ensemble (DME) is a technology-based interdisciplinary performance troupe that collaborates in the creation and performance of new works of art or performs historically innovative works. DME uses methods of open-ended critical inquiry to challenge meaning in the creation, realization and performance of art. The fall semester is usually focused on readings concerning the Labyrinth tradition in many cultures, culminating in the recurring work “Gypsy Pond Music,” a sonic, site-specific installation involving sculpture and algorithmic computer music.


DANCE 100 (modern dance) with Missy Beck. She's amazing.

MCDB 401 - protein folding with Jianming Li. This is niche. Protein folding is cool as fuck. Just read papers, present twice, and write about them for the midterm and final. I looooove writing and presenting and can't take multiple choice exams for shit, which is what almost all upper level MCDB classes are.



POLSCI 318- American Constitutional Politics with Mariah Zeisberg

Have you ever just spent a semester debating and then writing about slavery, voting rights, Citizens United, etc.? Just absolutely exhilarating.



Not a club but you should take PAT 200 - Intro to Electronic Music (or a more advanced PAT class if you already know the basics). Great class and a good time. Super chill and the professors are awesome. Highly recommend.Not a club but you should take PAT 200 - Intro to Electronic Music (or a more advanced PAT class if you already know the basics). Great class and a good time. Super chill and the professors are awesome. Highly recommend.


https://maizepages.umich.edu/organization/memco
michigan electronic music collective
