
200 applicants, 28 - 1? accepted
jerimiah - far left side of second slide - electrical and cs eng major, minor ross buiness school working at microsoft

ccsfp

minimum $1,500 to publish (research, etc.)
michelle ferrez went to ucla
always sit in first three to five rows
you should statements are generally bad
networking is important

the beauty of research is that flexibility is key
mistakes are expected


anastasila migrated in 2015

Colin Riker went to northwestern
nmc?
worked at tsa
doing research in nlp / machine learning

henry ford college

atom chetcuti is doing
dead seas scrolls project (with Dr. Anand?)


research is not a class
no syllabus, etc.

not knowing things is entirely expected
aka being overwhelmed by biology crash course is normal

you have every right to be here


sometimes phds talk at too high of a level since they
forget what it's like to learn the material for the first
time


community college teacher's number one priority: teaching
university teacher's number one priority: research, followed by teaching then "service"


pi
post doc
grad student

every ccsfp researcher experiences imposterism / imposter syndrome
feeling like you "conned" your way into your position
like you don't belong
don't have qualifications

A psychological pattern in which an individual doubts their skills, talents, or accomplishments and has a persistent internalized fear of being exposed as a "fraud".

A nagging feeling of inadequacy that prevents us from recognizing our value and success


( being judged on experiencing imposterism is very triggering )
looking like a fool has consequences ==> AAAAHHHHH
not ok to not know things
expected to learn decades of life experience in an instant
how people think of you does matter: single mistake is cataclysmic
relationship starts when you stop making mistakes
thinking that you can't make mistakes? that's a fatal flaw, sorry! you're not cOnfiDent!!


Studying at washtenaw community college
playing at redline percussion



attributes or identities you have that may increase or decrease feelings of imposterism
increase: feeling disconnected from others, not having cognitive power
decrease: feeling relaxed, undissociated / not emotionally triggered

george stuteville comes off as very confident, because he has a lot of
life experience and is very intellligent

being confident when you don't know something is
possibly the most confident you can be

one way to combat imposterism is to be in a supportive enviroment (no shit)

please ask questions!!

"The exaggerated esteem in which my lifework is held makes me very ill at ease. I feel compelled to think of myself as an involuntary swindler" - Albert Einstein

we're our biggest critics, we beat ourself's up a lot

# Logistics


35-40 - 5000
+1000 if commuting

living in dorm sucks lol
no time sheet for me to record, Michelle communicates with your Research Mentors to confirm your hours
